
# Configuración mínima para ReadTheDocs
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

# Especifica el builder de documentación
sphinx:
  configuration: docs/conf.py

# Dependencias de Python
python:
  install:
    - requirements: docs/requirements.txt
